### ISSUE TITLE
Omezení přístupu na web z hlediska dotace

### ISSUE THREAD

**Issue by Yendy** [Yendy/SPP#5]

**Comment by Kecul** [comment]
Preferované řešení za mě po konzultaci s Jerrym je neomezovat přístup. A odkaz šířit jen spolupracovníkům s poučením (zkušenost z podobných akcí, např. s novou podobou skautISu, se sdílenými google dokumenty). Kdo nemá odkaz, k SPP se nedostane, protože ve vyhledávačích lze dohledat složitě. Případně by bylo řešením zakázat indexování (vyloučit SPP z vyhledávání pomocí vyhledavačů úplně). Projektově možno jednoduše doložit.

**Comment by Yendy** [comment]
OK, to znamená, že aktuální stav webové aplikace zůstane beze změn. Pokud jsi s tím Marku v pohodě, uzavřu jako vyřešené

**Comment by Evangeliste1212** [comment]
Ok, ještě je nutné projekt znepřistůpnit vyhledávačům a pak už s tím budu cajk.
